version: '3.8'

services:
  db:  # データベースサービス
    image: postgres:15
    restart: always  # ✅ EC2再起動時も自動で起動
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:  # FastAPI アプリ側
    build: .
    restart: always  # ✅ 自動起動設定（←重要！）
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - .:/app

volumes:
  postgres_data: