name: Deploy to Railway

on:
  push:
    branches:
      - main  # mainブランチに push されたら動く

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ソースコードを取得
        uses: actions/checkout@v3

      - name: Python をセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 依存パッケージをインストール
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Railway にデプロイ
        uses: railwayapp/cli-action@v1
        with:
          command: up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}